apiVersion: apps/v1
kind: Deployment
metadata:
  name: argodeploy2
  namespace: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argodeploy2
  template:
    metadata:
      labels:
        app: argodeploy2
    spec:
      nodeSelector:
        kubernetes.io/arch: "arm64"
      containers:
      - name: argocontainer
        image: ekhari/newargodock:latest # Use the image from Docker Hub
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-mysql
              key: mysql-password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-mysql
              key: mysql-root-password
