apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-app-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: sample-app.cluster-test.salesconnection.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argodeploy2
            port:
              number: 5000
